apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-scripts
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  enable-ap.sh: {{ .Values.scripts.enableApSh | toYaml | indent 1 }}