---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-wifi-networking-platyplus-io-v1alpha1-accesspoint
  failurePolicy: Fail
  name: vaccesspoint.kb.io
  rules:
  - apiGroups:
    - wifi.networking.platyplus.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - accesspoints
  sideEffects: None
