apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wapop
namePrefix: wapop-

resources:
- daemonset.yaml
- namespace.yaml

configMapGenerator:
- files:
  - enable-ap.sh
  - disable-ap.sh
  name: scripts

generatorOptions:
  disableNameSuffixHash: true
