# permissions for end users to view accesspoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wapop
    app.kubernetes.io/managed-by: kustomize
  name: accesspoint-viewer-role
rules:
- apiGroups:
  - wifi.networking.platyplus.io
  resources:
  - accesspoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wifi.networking.platyplus.io
  resources:
  - accesspoints/status
  verbs:
  - get
