---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wifi.networking.platyplus.io
  resources:
  - accesspointnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wifi.networking.platyplus.io
  resources:
  - accesspointnodes/finalizers
  verbs:
  - update
- apiGroups:
  - wifi.networking.platyplus.io
  resources:
  - accesspointnodes/status
  verbs:
  - get
  - patch
  - update
