apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default
- secret.yaml
- https://github.com/stakater/Reloader/deployments/kubernetes

namespace: wapop

images:
- name: ap-manager
  newName: registry.suse.com/suse/sl-micro/6.0/baremetal-os-container
  newTag: 2.1.3-4.7

patches:
- path: daemonset.patch.yaml
  target:
    group: apps
    version: v1
    kind: DaemonSet
    name: daemonset
