apiVersion: v1
kind: Secret
metadata:
  name: wifi-settings
  namespace: wapop
stringData:
  psk: Pilette1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wifi-settings
  namespace: wapop
data:
  image: "registry.suse.com/suse/sl-micro/6.0/baremetal-os-container:2.1.3-4.7"
  ssid: rpi-tutu
  nodeSelector: |
    matchLabels:
      productName: "rpi"
